### ISSUE TITLE
The copy button hid in the copyright state.

### ISSUE THREAD

**Issue by chihuo2104** [baiyang-lzy/bbg#18]
Like this:
![@C)F3`SW%W69GW_(YQ$PJ8S](https://user-images.githubusercontent.com/38580503/174446516-224a815e-5a71-4cb8-9e1a-338a7215cd90.png)
Will fix it tomorrow?

**Comment by Misaka13514** [comment]
The current mobile style is not very good. To make that better we will have a lot to do.

**Comment by baiyang-lzy** [comment]
I think what @Misaka13514 said is right.

**Comment by chihuo2104** [comment]
Yep. I think I will fix it in 5 days.

**Comment by chihuo2104** [comment]
Oh,this is fixed.
