### ISSUE TITLE
Shall we use linters/formatters?

### ISSUE THREAD

**Issue by so1ve** [baiyang-lzy/bbg#20]
The current code of BBG is very difficult to read:

- extra blank lines
- extra/missing spaces
- extra/missing trailing comma
- irregular naming (camelCase or underscore_case)
- not using ESM's import/export or CommonJS's require/exports but using global variables

I think it is very important to use code linters.

**Comment by Misaka13514** [comment]
Personally I agree with you.
@baiyang-lzy What‘s your opinion?

@so1ve Can you help create a Pull Request if @baiyang-lzy approves?

**Comment by so1ve** [comment]
Maybe I can give it a try.
I'll use [@so1ve/eslint-config](https://npmjs.com/package/@so1ve/eslint-config)

**Comment by so1ve** [comment]
Fork ♂ it

**Comment by so1ve** [comment]
![](https://user-images.githubusercontent.com/58381667/176849829-1c331629-e2dc-4115-a04f-08c8fd0ddd8f.png)

Oops

**Comment by Misaka13514** [comment]
> ![](https://user-images.githubusercontent.com/58381667/176849829-1c331629-e2dc-4115-a04f-08c8fd0ddd8f.png)
> 
> Oops

Fight! Oh--(

**Comment by so1ve** [comment]
看来作者的代码风格很草（（

**Comment by so1ve** [comment]
Note:
```js
currentBlogVersion === undefined ||
  currentBlogVersion === null ||
  currentBlogVersion === ""
```
Equals to
```js
currentBlogVerson == null
```

**Comment by baiyang-lzy** [comment]
I think this is a good idea

**Comment by baiyang-lzy** [comment]
eslint configurations still need to be adjusted to adapt the code

**Comment by baiyang-lzy** [comment]
one method is to cancel some of the rules or set them to 'warning' level (not 'error')
the other method is to restruct many parts of the code

**Comment by chihuo2104** [comment]
This idea is very good (

**Comment by chihuo2104** [comment]
I suggested this a long ago?(x
But the author is get used to do this.（

**Comment by so1ve** [comment]
> eslint configurations still need to be adjusted to adapt the code

sure you can override the rules by yourself

**Comment by Misaka13514** [comment]
> > eslint configurations still need to be adjusted to adapt the code
> 
> sure you can override the rules by yourself

So maybe we will drop [@so1ve/eslint-config](https://npmjs.com/package/@so1ve/eslint-config).

**Comment by Misaka13514** [comment]
@so1ve seems something doesn't work as expected.
```
$ yarn
warning "@so1ve/eslint-config > eslint-config-standard@17.0.0-1" has incorrect peer dependency "eslint-plugin-n@^14.0.0".
warning "@so1ve/eslint-config > @so1ve/eslint-config-react > @so1ve/eslint-config-ts@0.21.5" has unmet peer dependency "typescript@>=3.9".
warning "@so1ve/eslint-config > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
```

```
$ yarn run lint
yarn run v1.22.15
$ eslint .

Oops! Something went wrong! :(

ESLint: 8.18.0

Error: Failed to load plugin '@typescript-eslint' declared in '.eslintrc » @so1ve/eslint-config » @so1ve/eslint-config-react » @so1ve/eslint-config-ts': Cannot find module 'typescript'
Require stack:
- /workspaces/bbg/node_modules/@typescript-eslint/eslint-plugin/dist/util/astUtils.js
- /workspaces/bbg/node_modules/@typescript-eslint/eslint-plugin/dist/util/index.js
- /workspaces/bbg/node_modules/@typescript-eslint/eslint-plugin/dist/rules/adjacent-overload-signatures.js
- /workspaces/bbg/node_modules/@typescript-eslint/eslint-plugin/dist/rules/index.js
- /workspaces/bbg/node_modules/@typescript-eslint/eslint-plugin/dist/index.js
- /workspaces/bbg/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
Referenced from: /workspaces/bbg/node_modules/@so1ve/eslint-config-ts/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/workspaces/bbg/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/workspaces/bbg/node_modules/@typescript-eslint/eslint-plugin/dist/util/astUtils.js:31:25)
    at Module._compile (/workspaces/bbg/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'd like to start from [eslint doc](https://eslint.org/docs/latest/user-guide/getting-started). Any ideas? @baiyang-lzy @so1ve

**Comment by baiyang-lzy** [comment]
try ```npm install typescript``` (in this project)

or install typescript globally (```npm install -g typescript```)

**Comment by Misaka13514** [comment]
but we don't use typescript at all(

**Comment by so1ve** [comment]
You can just modify the package by yourself or use @so1ve/eslint-config-basic

**Comment by chihuo2104** [comment]
Used .eslintrc.js copied from @so1ve/eslint-config-basic/index.js in 638c4ea

**Comment by chihuo2104** [comment]
This file will be suitable for bbg.

**Comment by Misaka13514** [comment]
but WIP and not yet fixed

**Comment by chihuo2104** [comment]
Yep（

**Comment by chihuo2104** [comment]
Successfully added. 3b53828
