### ISSUE TITLE
License changed to Unlicense License

### ISSUE THREAD

**Issue by Misaka13514** [baiyang-lzy/bbg#6]
Need all contributors agree.

- [x] @baiyang-lzy 
- [x] @chihuo2104 
- [x] @scientificworld 
- [x] @Misaka13514 
- [x] @mzwing

**Comment by chihuo2104** [comment]
I agree.

**Comment by mzwing** [comment]
I agree.

**Comment by scientificworld** [comment]
I think it's \*ao\*, and it has no disadvantages.
But why not use [The DFDT License](https://gitee.com/scientificworld/dfdt) :D

**Comment by baiyang-lzy** [comment]
> I think it's *ao*, and it has no disadvantages. But why not use [The DFDT License](https://gitee.com/scientificworld/dfdt) :D

I agree with you.

**Comment by baiyang-lzy** [comment]
> I think it's *ao*, and it has no disadvantages. But why not use [The DFDT License](https://gitee.com/scientificworld/dfdt) :D

However, ```dfdt``` is made from Neko Planet, so you cannot simply choose it from the License List given by GitHub.（
